openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8080/api
tags:
  - name: Download
    description: ファイルダウンロード
paths:
  /csv:
    get:
      summary: CSVダウンロード
      tags:
        - Download
      responses:
        "200":
          description: OK
          content:
            text/csv:
              schema:
                type: string
