openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8080/api
tags:
  - name: Download
    description: ファイルダウンロード
paths:
  /csv:
    get:
      summary: CSVダウンロード
      tags:
        - Download
      responses:
        "200":
          description: OK
          content:
            text/csv:
              schema:
                type: string
  /csv/sjis:
    get:
      summary: CSVダウンロード(sjis)
      tags:
        - Download
      responses:
        "200":
          description: OK
          content:
            text/csv; charset=Shift_JIS:
              schema:
                type: string
  /image:
    get:
      summary: 画像ダウンロード
      tags:
        - Download
      responses:
        "200":
          description: OK
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
  /image/jpeg_or_png:
    get:
      summary: 画像ダウンロード(jpeg or png)
      tags:
        - Download
      parameters:
        - in: query
          name: type
          required: true
          schema:
            $ref: "#/components/schemas/ImageType"
      responses:
        "200":
          description: OK
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
components:
  schemas:
    ImageType:
      type: string
      enum:
        - jpeg
        - png
